<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    public function up(): void
    {
        Schema::create('service_groups', function (Blueprint $table) {
            $table->id();
            $table->foreignId('category_id')->constrained('categories')->cascadeOnDelete();
            $table->string('name');
            // Globally unique slugs: salon-luxe, salon-prime, spa-ayurveda, spa-prime
            // Auto-generated by controller from category->slug + group name
            $table->string('slug')->unique();
            $table->string('tag_label')->nullable(); // e.g. "Premium", "Bestseller"
            $table->text('description')->nullable();
            $table->string('image')->nullable();
            $table->enum('status', ['Active', 'Inactive'])->default('Active');
            $table->unsignedInteger('sort_order')->default(0);
            $table->timestamps();

            // Composite index for common API query: active groups for a category, ordered
            $table->index(['category_id', 'status', 'sort_order']);
        });
    }

    public function down(): void
    {
        Schema::dropIfExists('service_groups');
    }
};
